-- ADDING COLUMNS

-- CREATE TABLE COMPANIES (
-- 	NAME VARCHAR(255) NOT NULL,
--     ADDRESS VARCHAR(255) NOT NULL,
--     CONSTRAINT name_address UNIQUE(NAME, ADDRESS)
-- );

INSERT INTO COMPANIES (NAME, ADDRESS) VALUES ('FACEBOOK', 'NEW YORK');


ALTER TABLE COMPANIES
ADD COLUMN PHONE VARCHAR(15);


SELECT * FROM COMPANIES;


ALTER TABLE COMPANIES
ADD COLUMN EMPLOYEE_COUNT INT NOT NULL;



-- DROPPING COLUMNS
ALTER TABLE companies DROP COLUMN phone;

-- RENAMING
RENAME TABLE COMPANIES TO SUPPLIERS;

ALTER TABLE SUPPLIERS RENAME TO COMPANIES;

-- RENAMING COLUMNS
ALTER TABLE COMPANIES 
RENAME COLUMN NAME TO COMPANY_NAME;

-- MODIFYING COLUMNS
ALTER TABLE COMPANIES
MODIFY COMPANY_NAME VARCHAR(155) DEFAULT 'NONE';

DESC COMPANIES;



-- MODIFYING CONSTRAINTS
ALTER TABLE houses 
ADD CONSTRAINT positive_pprice CHECK (purchase_price >= 0);

ALTER TABLE HOUSES
DROP CONSTRAINT POSITIVE_PPRICE;








