-- COUNT

-- COUNT NUMBER OF RECORDS
USE BOOK_SHOP;
SELECT COUNT(*) FROM BOOKS;

SELECT COUNT(DISTINCT(AUTHOR_FNAME)) FROM BOOKS;

SELECT COUNT(TITLE)
FROM BOOKS
WHERE TITLE LIKE '%The%';



-- GROUP BY

SELECT AUTHOR_LNAME 
FROM BOOKS 
GROUP BY AUTHOR_LNAME;



-- COUNT BOOKS BY EACH AUTHOR

SELECT AUTHOR_LNAME, COUNT(*) AS BOOKS_WRITTEN
FROM BOOKS
GROUP BY AUTHOR_LNAME
ORDER BY BOOKS_WRITTEN;


SELECT RELEASED_YEAR, COUNT(*) 
FROM BOOKS
GROUP BY RELEASED_YEAR;



-- MIN AND MAX
SELECT MAX(pages) FROM books;
 
SELECT MIN(author_lname) FROM books;



-- SUBQUERIES : QUERY WITHIN QUERY
-- SELECT BOOKS WITH MAX PAGES;

SELECT * FROM BOOKS ORDER BY PAGES DESC LIMIT 1;

-- OTHER WAY
SELECT * 
FROM BOOKS
WHERE PAGES = ( 
	SELECT MAX(PAGES) FROM BOOKS
);


-- SELECT TITLE OF EARLIEST RELEASED BOOKS
SELECT TITLE, MIN(RELEASED_YEAR) 
FROM BOOKS
WHERE RELEASED_YEAR = (
	SELECT MIN(RELEASED_YEAR)
    FROM BOOKS
);



-- group by multiple columns
SELECT CONCAT(AUTHOR_FNAME, ' ', AUTHOR_LNAME) AS FULLNAME, COUNT(*)
FROM BOOKS
GROUP BY FULLNAME;

-- GROUP BY MIN, MAX
SELECT CONCAT(AUTHOR_FNAME, ' ', AUTHOR_LNAME) AS FULLNAME, COUNT(*),  MIN(RELEASED_YEAR), MAX(RELEASED_YEAR)
FROM BOOKS
GROUP BY FULLNAME;

-- sum
select sum(pages)
from books;


SELECT  CONCAT(AUTHOR_FNAME, ' ', AUTHOR_LNAME) AS NAME, SUM(PAGES) AS PAGES_WRITTEN
FROM BOOKS
GROUP BY NAME;





