-- SUBTRACT SECOND FROM THE FIRST

-- HOW MANY DAYS AGO SOMEONE WAS BORN
SELECT DATEDIFF(NOW(), BIRTHDT) FROM PEOPLE;

-- DATE ADD
SELECT DATE_ADD(NOW(), INTERVAL -700 DAY);
SELECT DATE_ADD(CURDATE(), INTERVAL 7 DAY);

-- DATE SUB
SELECT DATE_SUB(NOW(), INTERVAL 5 DAY);