-- DATE FUNCTIONS

-- GIVES DATE
SELECT BIRTHDATE, DAY(BIRTHDATE) FROM PEOPLE; 


-- GIVES WEEK DAY 1 -> SUNDAY, 2 -> MONDAY, ... , 7 -> SATURDAY
SELECT BIRTHDATE, DAYOFWEEK(BIRTHDATE) FROM PEOPLE; 


-- GET DAY OF THE YEAR
SELECT BIRTHDATE, DAYOFYEAR(BIRTHDATE) FROM PEOPLE; 

-- GET MONTHNAME
SELECT BIRTHDATE, MONTHNAME(BIRTHDATE) FROM PEOPLE; 


-- WEEK() RETURNS THE WEEK OF THE YEAR
-- YEAR(BIRTHDT) RETURNS YEAR
-- MONTHNAME(DATE) RETURNS MONTHNAME



-- TIME FUNCTIONS()

SELECT BIRTHDT , HOUR(BIRTHDT) AS HR, MINUTE(BIRTHDT) AS MINS, SECOND(BIRTHDT) AS SECS
FROM PEOPLE;
 
SELECT BIRTHDT, DATE(BIRTHDT) AS BIRTHDATE, TIME(BIRTHDT) AS BIRTHTIME
FROM PEOPLE;


